import asyncio
import json
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import httpx
from helper import get_gemini_api_key, get_ai_or_not_api_key
from fastapi import HTTPException
from google import genai
from google.genai import types
from PIL import Image
from io import BytesIO

gemini_client = genai.Client(api_key=get_gemini_api_key())
MODEL = "gemini-2.5-flash"

ANALYSIS_PROMPT = """You are an AI image detection expert. Analyze this image and determine whether it was likely generated by an AI (e.g. Midjourney, DALL-E, Stable Diffusion, etc.) or is a real photograph.

Return a JSON object with exactly these fields:

{
  "verdict": "likely_real" | "uncertain" | "likely_ai",
  "ai_score": <integer 0-100, where 100 = definitely AI-generated>,
  "signals": [<list of specific visual patterns that support your assessment>],
  "summary": "<2-3 sentence plain English explanation of your findings>"
}

Important rules:
- signals should be specific observations like "unnatural skin texture", "perfect symmetric lighting",
  "distorted hands/fingers", "overly smooth backgrounds", "hallucinated text", "photorealistic but uncanny"
- Never claim an image IS definitively AI-generated, only flag likelihood
- Return valid JSON only, no markdown, no explanation outside the JSON
"""


async def analyze_image_url(url: str) -> dict:
    """Call aiornot API (for score) and Gemini (for explanation) in parallel."""
    aiornot_key = get_ai_or_not_api_key()

    async def call_aiornot():
        async with httpx.AsyncClient(timeout=30.0) as client:
            res = await client.post(
                "https://api.aiornot.com/v2/image/sync",
                headers={"Authorization": f"Bearer {aiornot_key}", "Content-Type": "application/json"},
                json={"url": url},
            )
            res.raise_for_status()
            return res.json()

    async def call_gemini():
        async with httpx.AsyncClient(timeout=30.0) as client:
            res = await client.get(url)
            res.raise_for_status()
            image_bytes = res.content
            mime_type = res.headers.get("content-type", "image/jpeg").split(";")[0]
        return await analyze_image(image_bytes, mime_type)

    aiornot_result, gemini_result = await asyncio.gather(
        call_aiornot(), call_gemini(), return_exceptions=True
    )

    result = {}
    if not isinstance(aiornot_result, Exception):
        result.update(aiornot_result)
    else:
        raise HTTPException(status_code=502, detail=f"AI-or-Not error: {aiornot_result}")

    if not isinstance(gemini_result, Exception):
        result["gemini_summary"] = gemini_result.get("summary")
        result["gemini_verdict"] = gemini_result.get("verdict")
        result["gemini_ai_score"] = gemini_result.get("ai_score")
        result["gemini_signals"] = gemini_result.get("signals", [])

    return result


async def analyze_image(image_bytes: bytes, mime_type: str) -> dict:
    try:
        pil_image = Image.open(BytesIO(image_bytes))
    except Exception:
        raise HTTPException(status_code=400, detail="Could not decode image file")

    try:
        response = await asyncio.to_thread(
            gemini_client.models.generate_content,
            model=MODEL,
            contents=[ANALYSIS_PROMPT, pil_image],
        )

        raw = response.text.strip()

        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        return json.loads(raw)

    except json.JSONDecodeError:
        raise HTTPException(status_code=500, detail="Gemini returned malformed JSON")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Gemini error: {str(e)}")
