import asyncio
import json
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import httpx
from helper import get_gemini_api_key, get_ai_or_not_api_key
from fastapi import HTTPException
from google import genai
from google.genai import types
from PIL import Image
from io import BytesIO

gemini_client = genai.Client(api_key=get_gemini_api_key())
MODEL = "gemini-2.5-flash"

ANALYSIS_PROMPT = """You are an AI image detection expert. Analyze this image and determine whether it was likely generated by an AI (e.g. Midjourney, DALL-E, Stable Diffusion, etc.) or is a real photograph.

Return a JSON object with exactly these fields:

{
  "verdict": "likely_real" | "uncertain" | "likely_ai",
  "ai_score": <integer 0-100, where 100 = definitely AI-generated>,
  "signals": [<list of specific visual patterns that support your assessment>],
  "summary": "<2-3 sentence plain English explanation of your findings>"
}

Important rules:
- signals should be specific observations like "unnatural skin texture", "perfect symmetric lighting",
  "distorted hands/fingers", "overly smooth backgrounds", "hallucinated text", "photorealistic but uncanny"
- Never claim an image IS definitively AI-generated, only flag likelihood
- Return valid JSON only, no markdown, no explanation outside the JSON
"""


async def analyze_image_url(url: str) -> dict:
    """Call aiornot API (for score) and Gemini (for explanation) in parallel."""
    aiornot_key = get_ai_or_not_api_key()

    async def call_aiornot():
        async with httpx.AsyncClient(timeout=30.0) as client:
            res = await client.post(
                "https://api.aiornot.com/v2/image/sync",
                headers={"Authorization": f"Bearer {aiornot_key}", "Content-Type": "application/json"},
                json={"url": url},
            )
            res.raise_for_status()
            return res.json()

    async def call_gemini():
        async with httpx.AsyncClient(timeout=30.0) as client:
            res = await client.get(url)
            res.raise_for_status()
            image_bytes = res.content
            mime_type = res.headers.get("content-type", "image/jpeg").split(";")[0]
        return await analyze_image(image_bytes, mime_type)

    aiornot_result, gemini_result = await asyncio.gather(
        call_aiornot(), call_gemini(), return_exceptions=True
    )

    result = {}
    if not isinstance(aiornot_result, Exception):
        result.update(aiornot_result)
    else:
        raise HTTPException(status_code=502, detail=f"AI-or-Not error: {aiornot_result}")

    if not isinstance(gemini_result, Exception):
        result["gemini_summary"] = gemini_result.get("summary")
        result["gemini_verdict"] = gemini_result.get("verdict")
        result["gemini_ai_score"] = gemini_result.get("ai_score")
        result["gemini_signals"] = gemini_result.get("signals", [])

    return result


async def analyze_image(image_bytes: bytes, mime_type: str) -> dict:
    try:
        pil_image = Image.open(BytesIO(image_bytes))
    except Exception:
        raise HTTPException(status_code=400, detail="Could not decode image file")

    try:
        response = await asyncio.to_thread(
            gemini_client.models.generate_content,
            model=MODEL,
            contents=[ANALYSIS_PROMPT, pil_image],
        )

        raw = response.text.strip()

        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        return json.loads(raw)

    except json.JSONDecodeError:
        raise HTTPException(status_code=500, detail="Gemini returned malformed JSON")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Gemini error: {str(e)}")
import io
from PIL import Image
from fastapi import HTTPException
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from helper import get_ai_or_not_api_key, get_gemini_api_key
from PIL import Image
from google import genai
from google.genai import types


API_KEY = get_ai_or_not_api_key()
IMAGE_ENDPOINT = "https://api.aiornot.com/v2/image/sync"


async def analyze_from_upload(file):
    async with httpx.AsyncClient() as client:
        contents = await file.read()
        response = await client.post(
            IMAGE_ENDPOINT,
            headers={"Authorization": f"Bearer {API_KEY}"},
            files={"image": (file.filename, contents, file.content_type)}
        )
        return response.json()


async def analyze_from_url(url: str):
    async with httpx.AsyncClient(follow_redirects=True) as client:
        try:
            image_response = await client.get(url)
            image_response.raise_for_status()
        except httpx.HTTPStatusError:
            raise HTTPException(status_code=400, detail="Could not fetch image from URL")
        except httpx.RequestError:
            raise HTTPException(status_code=400, detail="Invalid URL or network error")

        try:
            image = Image.open(io.BytesIO(image_response.content))
            buffer = io.BytesIO()
            image.convert("RGB").save(buffer, format="JPEG")
            buffer.seek(0)
        except Exception:
            raise HTTPException(status_code=400, detail="URL does not point to a valid image")

        response = await client.post(
            IMAGE_ENDPOINT,
            headers={"Authorization": f"Bearer {API_KEY}"},
            files={"image": ("image.jpg", buffer, "image/jpeg")}
        )
        return response.json()


_gemini_client = None

def _get_gemini_client():
    global _gemini_client
    if _gemini_client is None:
        _gemini_client = genai.Client(api_key=get_gemini_api_key())
    return _gemini_client

# Add these two new functions
async def analyze_image_with_gemini(image_input) -> str:
    if isinstance(image_input, str):
        async with httpx.AsyncClient() as client:
            resp = await client.get(image_input)
            resp.raise_for_status()
        image = Image.open(io.BytesIO(resp.content))
    else:
        image = image_input

    response = _get_gemini_client().models.generate_content(
        model="gemini-2.5-flash",
        contents=[
            "In 30 words or less explain if this image is AI generated or not and why.",
            image
        ]
    )
    return response.text

async def analyze_youtube_with_gemini(url: str) -> str:
    response = _get_gemini_client().models.generate_content(
        model="gemini-2.5-flash",
        contents=types.Content(
            parts=[
                types.Part(file_data=types.FileData(file_uri=url)),
                types.Part(text="Analyze this video and determine if it was made with or by AI. Look for signs like unnatural movements, inconsistent lighting, strange audio, digital artifacts, or anything else that suggests AI generation. Give a clear verdict and explain your reasoning.")
            ]
        )
    )
    return response.text

if __name__ == "__main__":
    import asyncio
    from dotenv import load_dotenv
    load_dotenv(os.path.join(os.path.dirname(__file__), "..", "apikeys.env"))

    TEST_URL = "https://imgs.search.brave.com/Nzcp5Y68K10t7ezK83y8_sgJzKZjXndFUy5_CLo8zJQ/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMubmlnaHRjYWZl/LnN0dWRpby8vYXNz/ZXRzL2JlYWNoLWV5/ZS5qcGc_dHI9dy0x/NjAwLGMtYXRfbWF4"

    result = asyncio.run(analyze_from_url(TEST_URL))
    print(result)
